
CREATE TABLE EVENT(ID INT PRIMARY KEY, EVENT_NAME VARCHAR(255),EVENT_DESCRIPTION VARCHAR(4000),
EVENT_DATE DATE, VENUE VARCHAR(255));

CREATE TABLE EVENT_SUBSCRIPTION(ID INT PRIMARY KEY,EVENT_ID INT ,USER_NAME VARCHAR(255),
IS_SUBSCRIBED varchar(10), SUBSCRIPTION_DATE DATE);